/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RevisorRouteImport } from './routes/revisor'
import { Route as JuridicoRouteImport } from './routes/juridico'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ConfiguracaoGeralRouteImport } from './routes/configuracao-geral'
import { Route as ControladoriaRouteImport } from './routes/controladoria'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RevisorIndexRouteImport } from './routes/revisor.index'
import { Route as JuridicoProjetosRouteImport } from './routes/juridico.projetos'
import { Route as JuridicoPreProjetosRouteImport } from './routes/juridico.pre-projetos'
import { Route as JuridicoIndexRouteImport } from './routes/juridico.index'
import { Route as JuridicoAgrupamentosRouteImport } from './routes/juridico.agrupamentos'
import { Route as FinanceiroIndexRouteImport } from './routes/financeiro.index'
import { Route as ControladoriaIndexRouteImport } from './routes/controladoria.index'
import { Route as ConfiguracaoGeralPesquisadoresRouteImport } from './routes/configuracao-geral.pesquisadores'
import { Route as ConfiguracaoGeralPerguntasRouteImport } from './routes/configuracao-geral.perguntas'
import { Route as ConfiguracaoGeralIndexRouteImport } from './routes/configuracao-geral.index'
import { Route as ConfiguracaoGeralCargosRouteImport } from './routes/configuracao-geral.cargos'
import { Route as ControladoriaIniciativasRouteImport } from './routes/controladoria.iniciativas'
import { Route as ControladoriaContasContabeisRouteImport } from './routes/controladoria.contas-contabeis'
import { Route as ControladoriaConfiguracoesRouteImport } from './routes/controladoria.configuracoes'
import { Route as ProjetosNovoRouteImport } from './routes/projetos.novo'
import { Route as ProjetosIdRouteImport } from './routes/projetos.$id'
import { Route as RevisorProjetosIdRouteImport } from './routes/revisor.projetos.$id'
import { Route as FinanceiroProjetosIdRouteImport } from './routes/financeiro.projetos.$id'

const RevisorRoute = RevisorRouteImport.update({
  id: '/revisor',
  path: '/revisor',
  getParentRoute: () => rootRouteImport,
} as any)
const JuridicoRoute = JuridicoRouteImport.update({
  id: '/juridico',
  path: '/juridico',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracaoGeralRoute = ConfiguracaoGeralRouteImport.update({
  id: '/configuracao-geral',
  path: '/configuracao-geral',
  getParentRoute: () => rootRouteImport,
} as any)
const ControladoriaRoute = ControladoriaRouteImport.update({
  id: '/controladoria',
  path: '/controladoria',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisorIndexRoute = RevisorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RevisorRoute,
} as any)
const JuridicoProjetosRoute = JuridicoProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => JuridicoRoute,
} as any)
const JuridicoPreProjetosRoute = JuridicoPreProjetosRouteImport.update({
  id: '/pre-projetos',
  path: '/pre-projetos',
  getParentRoute: () => JuridicoRoute,
} as any)
const JuridicoIndexRoute = JuridicoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JuridicoRoute,
} as any)
const JuridicoAgrupamentosRoute = JuridicoAgrupamentosRouteImport.update({
  id: '/agrupamentos',
  path: '/agrupamentos',
  getParentRoute: () => JuridicoRoute,
} as any)
const FinanceiroIndexRoute = FinanceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceiroRoute,
} as any)
const ControladoriaIndexRoute = ControladoriaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ControladoriaRoute,
} as any)
const ConfiguracaoGeralPesquisadoresRoute =
  ConfiguracaoGeralPesquisadoresRouteImport.update({
    id: '/pesquisadores',
    path: '/pesquisadores',
    getParentRoute: () => ConfiguracaoGeralRoute,
  } as any)
const ConfiguracaoGeralPerguntasRoute =
  ConfiguracaoGeralPerguntasRouteImport.update({
    id: '/perguntas',
    path: '/perguntas',
    getParentRoute: () => ConfiguracaoGeralRoute,
  } as any)
const ConfiguracaoGeralIndexRoute = ConfiguracaoGeralIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConfiguracaoGeralRoute,
} as any)
const ConfiguracaoGeralCargosRoute = ConfiguracaoGeralCargosRouteImport.update({
  id: '/cargos',
  path: '/cargos',
  getParentRoute: () => ConfiguracaoGeralRoute,
} as any)
const ControladoriaIniciativasRoute =
  ControladoriaIniciativasRouteImport.update({
    id: '/iniciativas',
    path: '/iniciativas',
    getParentRoute: () => ControladoriaRoute,
  } as any)
const ControladoriaContasContabeisRoute =
  ControladoriaContasContabeisRouteImport.update({
    id: '/contas-contabeis',
    path: '/contas-contabeis',
    getParentRoute: () => ControladoriaRoute,
  } as any)
const ControladoriaConfiguracoesRoute =
  ControladoriaConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => ControladoriaRoute,
  } as any)
const ProjetosNovoRoute = ProjetosNovoRouteImport.update({
  id: '/projetos/novo',
  path: '/projetos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdRoute = ProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisorProjetosIdRoute = RevisorProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => RevisorRoute,
} as any)
const FinanceiroProjetosIdRoute = FinanceiroProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => FinanceiroRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/controladoria': typeof ControladoriaRouteWithChildren
  '/configuracao-geral': typeof ConfiguracaoGeralRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/juridico': typeof JuridicoRouteWithChildren
  '/revisor': typeof RevisorRouteWithChildren
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/controladoria/configuracoes': typeof ControladoriaConfiguracoesRoute
  '/controladoria/contas-contabeis': typeof ControladoriaContasContabeisRoute
  '/controladoria/iniciativas': typeof ControladoriaIniciativasRoute
  '/configuracao-geral/cargos': typeof ConfiguracaoGeralCargosRoute
  '/configuracao-geral/': typeof ConfiguracaoGeralIndexRoute
  '/configuracao-geral/perguntas': typeof ConfiguracaoGeralPerguntasRoute
  '/configuracao-geral/pesquisadores': typeof ConfiguracaoGeralPesquisadoresRoute
  '/controladoria/': typeof ControladoriaIndexRoute
  '/financeiro/': typeof FinanceiroIndexRoute
  '/juridico/agrupamentos': typeof JuridicoAgrupamentosRoute
  '/juridico/': typeof JuridicoIndexRoute
  '/juridico/pre-projetos': typeof JuridicoPreProjetosRoute
  '/juridico/projetos': typeof JuridicoProjetosRoute
  '/revisor/': typeof RevisorIndexRoute
  '/financeiro/projetos/$id': typeof FinanceiroProjetosIdRoute
  '/revisor/projetos/$id': typeof RevisorProjetosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/controladoria/configuracoes': typeof ControladoriaConfiguracoesRoute
  '/controladoria/contas-contabeis': typeof ControladoriaContasContabeisRoute
  '/controladoria/iniciativas': typeof ControladoriaIniciativasRoute
  '/configuracao-geral/cargos': typeof ConfiguracaoGeralCargosRoute
  '/configuracao-geral': typeof ConfiguracaoGeralIndexRoute
  '/configuracao-geral/perguntas': typeof ConfiguracaoGeralPerguntasRoute
  '/configuracao-geral/pesquisadores': typeof ConfiguracaoGeralPesquisadoresRoute
  '/controladoria': typeof ControladoriaIndexRoute
  '/financeiro': typeof FinanceiroIndexRoute
  '/juridico/agrupamentos': typeof JuridicoAgrupamentosRoute
  '/juridico': typeof JuridicoIndexRoute
  '/juridico/pre-projetos': typeof JuridicoPreProjetosRoute
  '/juridico/projetos': typeof JuridicoProjetosRoute
  '/revisor': typeof RevisorIndexRoute
  '/financeiro/projetos/$id': typeof FinanceiroProjetosIdRoute
  '/revisor/projetos/$id': typeof RevisorProjetosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/controladoria': typeof ControladoriaRouteWithChildren
  '/configuracao-geral': typeof ConfiguracaoGeralRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/juridico': typeof JuridicoRouteWithChildren
  '/revisor': typeof RevisorRouteWithChildren
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/controladoria/configuracoes': typeof ControladoriaConfiguracoesRoute
  '/controladoria/contas-contabeis': typeof ControladoriaContasContabeisRoute
  '/controladoria/iniciativas': typeof ControladoriaIniciativasRoute
  '/configuracao-geral/cargos': typeof ConfiguracaoGeralCargosRoute
  '/configuracao-geral/': typeof ConfiguracaoGeralIndexRoute
  '/configuracao-geral/perguntas': typeof ConfiguracaoGeralPerguntasRoute
  '/configuracao-geral/pesquisadores': typeof ConfiguracaoGeralPesquisadoresRoute
  '/controladoria/': typeof ControladoriaIndexRoute
  '/financeiro/': typeof FinanceiroIndexRoute
  '/juridico/agrupamentos': typeof JuridicoAgrupamentosRoute
  '/juridico/': typeof JuridicoIndexRoute
  '/juridico/pre-projetos': typeof JuridicoPreProjetosRoute
  '/juridico/projetos': typeof JuridicoProjetosRoute
  '/revisor/': typeof RevisorIndexRoute
  '/financeiro/projetos/$id': typeof FinanceiroProjetosIdRoute
  '/revisor/projetos/$id': typeof RevisorProjetosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/controladoria'
    | '/configuracao-geral'
    | '/dashboard'
    | '/financeiro'
    | '/juridico'
    | '/revisor'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/controladoria/configuracoes'
    | '/controladoria/contas-contabeis'
    | '/controladoria/iniciativas'
    | '/configuracao-geral/cargos'
    | '/configuracao-geral/'
    | '/configuracao-geral/perguntas'
    | '/configuracao-geral/pesquisadores'
    | '/controladoria/'
    | '/financeiro/'
    | '/juridico/agrupamentos'
    | '/juridico/'
    | '/juridico/pre-projetos'
    | '/juridico/projetos'
    | '/revisor/'
    | '/financeiro/projetos/$id'
    | '/revisor/projetos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/controladoria/configuracoes'
    | '/controladoria/contas-contabeis'
    | '/controladoria/iniciativas'
    | '/configuracao-geral/cargos'
    | '/configuracao-geral'
    | '/configuracao-geral/perguntas'
    | '/configuracao-geral/pesquisadores'
    | '/controladoria'
    | '/financeiro'
    | '/juridico/agrupamentos'
    | '/juridico'
    | '/juridico/pre-projetos'
    | '/juridico/projetos'
    | '/revisor'
    | '/financeiro/projetos/$id'
    | '/revisor/projetos/$id'
  id:
    | '__root__'
    | '/'
    | '/controladoria'
    | '/configuracao-geral'
    | '/dashboard'
    | '/financeiro'
    | '/juridico'
    | '/revisor'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/controladoria/configuracoes'
    | '/controladoria/contas-contabeis'
    | '/controladoria/iniciativas'
    | '/configuracao-geral/cargos'
    | '/configuracao-geral/'
    | '/configuracao-geral/perguntas'
    | '/configuracao-geral/pesquisadores'
    | '/controladoria/'
    | '/financeiro/'
    | '/juridico/agrupamentos'
    | '/juridico/'
    | '/juridico/pre-projetos'
    | '/juridico/projetos'
    | '/revisor/'
    | '/financeiro/projetos/$id'
    | '/revisor/projetos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControladoriaRoute: typeof ControladoriaRouteWithChildren
  ConfiguracaoGeralRoute: typeof ConfiguracaoGeralRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FinanceiroRoute: typeof FinanceiroRouteWithChildren
  JuridicoRoute: typeof JuridicoRouteWithChildren
  RevisorRoute: typeof RevisorRouteWithChildren
  ProjetosIdRoute: typeof ProjetosIdRoute
  ProjetosNovoRoute: typeof ProjetosNovoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/revisor': {
      id: '/revisor'
      path: '/revisor'
      fullPath: '/revisor'
      preLoaderRoute: typeof RevisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juridico': {
      id: '/juridico'
      path: '/juridico'
      fullPath: '/juridico'
      preLoaderRoute: typeof JuridicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracao-geral': {
      id: '/configuracao-geral'
      path: '/configuracao-geral'
      fullPath: '/configuracao-geral'
      preLoaderRoute: typeof ConfiguracaoGeralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controladoria': {
      id: '/controladoria'
      path: '/controladoria'
      fullPath: '/controladoria'
      preLoaderRoute: typeof ControladoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisor/': {
      id: '/revisor/'
      path: '/'
      fullPath: '/revisor/'
      preLoaderRoute: typeof RevisorIndexRouteImport
      parentRoute: typeof RevisorRoute
    }
    '/juridico/projetos': {
      id: '/juridico/projetos'
      path: '/projetos'
      fullPath: '/juridico/projetos'
      preLoaderRoute: typeof JuridicoProjetosRouteImport
      parentRoute: typeof JuridicoRoute
    }
    '/juridico/pre-projetos': {
      id: '/juridico/pre-projetos'
      path: '/pre-projetos'
      fullPath: '/juridico/pre-projetos'
      preLoaderRoute: typeof JuridicoPreProjetosRouteImport
      parentRoute: typeof JuridicoRoute
    }
    '/juridico/': {
      id: '/juridico/'
      path: '/'
      fullPath: '/juridico/'
      preLoaderRoute: typeof JuridicoIndexRouteImport
      parentRoute: typeof JuridicoRoute
    }
    '/juridico/agrupamentos': {
      id: '/juridico/agrupamentos'
      path: '/agrupamentos'
      fullPath: '/juridico/agrupamentos'
      preLoaderRoute: typeof JuridicoAgrupamentosRouteImport
      parentRoute: typeof JuridicoRoute
    }
    '/financeiro/': {
      id: '/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof FinanceiroIndexRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/controladoria/': {
      id: '/controladoria/'
      path: '/'
      fullPath: '/controladoria/'
      preLoaderRoute: typeof ControladoriaIndexRouteImport
      parentRoute: typeof ControladoriaRoute
    }
    '/configuracao-geral/pesquisadores': {
      id: '/configuracao-geral/pesquisadores'
      path: '/pesquisadores'
      fullPath: '/configuracao-geral/pesquisadores'
      preLoaderRoute: typeof ConfiguracaoGeralPesquisadoresRouteImport
      parentRoute: typeof ConfiguracaoGeralRoute
    }
    '/configuracao-geral/perguntas': {
      id: '/configuracao-geral/perguntas'
      path: '/perguntas'
      fullPath: '/configuracao-geral/perguntas'
      preLoaderRoute: typeof ConfiguracaoGeralPerguntasRouteImport
      parentRoute: typeof ConfiguracaoGeralRoute
    }
    '/configuracao-geral/': {
      id: '/configuracao-geral/'
      path: '/'
      fullPath: '/configuracao-geral/'
      preLoaderRoute: typeof ConfiguracaoGeralIndexRouteImport
      parentRoute: typeof ConfiguracaoGeralRoute
    }
    '/configuracao-geral/cargos': {
      id: '/configuracao-geral/cargos'
      path: '/cargos'
      fullPath: '/configuracao-geral/cargos'
      preLoaderRoute: typeof ConfiguracaoGeralCargosRouteImport
      parentRoute: typeof ConfiguracaoGeralRoute
    }
    '/controladoria/iniciativas': {
      id: '/controladoria/iniciativas'
      path: '/iniciativas'
      fullPath: '/controladoria/iniciativas'
      preLoaderRoute: typeof ControladoriaIniciativasRouteImport
      parentRoute: typeof ControladoriaRoute
    }
    '/controladoria/contas-contabeis': {
      id: '/controladoria/contas-contabeis'
      path: '/contas-contabeis'
      fullPath: '/controladoria/contas-contabeis'
      preLoaderRoute: typeof ControladoriaContasContabeisRouteImport
      parentRoute: typeof ControladoriaRoute
    }
    '/controladoria/configuracoes': {
      id: '/controladoria/configuracoes'
      path: '/configuracoes'
      fullPath: '/controladoria/configuracoes'
      preLoaderRoute: typeof ControladoriaConfiguracoesRouteImport
      parentRoute: typeof ControladoriaRoute
    }
    '/projetos/novo': {
      id: '/projetos/novo'
      path: '/projetos/novo'
      fullPath: '/projetos/novo'
      preLoaderRoute: typeof ProjetosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$id': {
      id: '/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof ProjetosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisor/projetos/$id': {
      id: '/revisor/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/revisor/projetos/$id'
      preLoaderRoute: typeof RevisorProjetosIdRouteImport
      parentRoute: typeof RevisorRoute
    }
    '/financeiro/projetos/$id': {
      id: '/financeiro/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/financeiro/projetos/$id'
      preLoaderRoute: typeof FinanceiroProjetosIdRouteImport
      parentRoute: typeof FinanceiroRoute
    }
  }
}

interface FinanceiroRouteChildren {
  FinanceiroIndexRoute: typeof FinanceiroIndexRoute
  FinanceiroProjetosIdRoute: typeof FinanceiroProjetosIdRoute
}

const FinanceiroRouteChildren: FinanceiroRouteChildren = {
  FinanceiroIndexRoute: FinanceiroIndexRoute,
  FinanceiroProjetosIdRoute: FinanceiroProjetosIdRoute,
}

const FinanceiroRouteWithChildren = FinanceiroRoute._addFileChildren(
  FinanceiroRouteChildren,
)

interface JuridicoRouteChildren {
  JuridicoAgrupamentosRoute: typeof JuridicoAgrupamentosRoute
  JuridicoIndexRoute: typeof JuridicoIndexRoute
  JuridicoPreProjetosRoute: typeof JuridicoPreProjetosRoute
  JuridicoProjetosRoute: typeof JuridicoProjetosRoute
}

const JuridicoRouteChildren: JuridicoRouteChildren = {
  JuridicoAgrupamentosRoute: JuridicoAgrupamentosRoute,
  JuridicoIndexRoute: JuridicoIndexRoute,
  JuridicoPreProjetosRoute: JuridicoPreProjetosRoute,
  JuridicoProjetosRoute: JuridicoProjetosRoute,
}

const JuridicoRouteWithChildren = JuridicoRoute._addFileChildren(
  JuridicoRouteChildren,
)

interface RevisorRouteChildren {
  RevisorIndexRoute: typeof RevisorIndexRoute
  RevisorProjetosIdRoute: typeof RevisorProjetosIdRoute
}

const RevisorRouteChildren: RevisorRouteChildren = {
  RevisorIndexRoute: RevisorIndexRoute,
  RevisorProjetosIdRoute: RevisorProjetosIdRoute,
}

const RevisorRouteWithChildren =
  RevisorRoute._addFileChildren(RevisorRouteChildren)

interface ControladoriaRouteChildren {
  ControladoriaIndexRoute: typeof ControladoriaIndexRoute
  ControladoriaConfiguracoesRoute: typeof ControladoriaConfiguracoesRoute
  ControladoriaContasContabeisRoute: typeof ControladoriaContasContabeisRoute
  ControladoriaIniciativasRoute: typeof ControladoriaIniciativasRoute
}

const ControladoriaRouteChildren: ControladoriaRouteChildren = {
  ControladoriaIndexRoute: ControladoriaIndexRoute,
  ControladoriaConfiguracoesRoute: ControladoriaConfiguracoesRoute,
  ControladoriaContasContabeisRoute: ControladoriaContasContabeisRoute,
  ControladoriaIniciativasRoute: ControladoriaIniciativasRoute,
}

const ControladoriaRouteWithChildren = ControladoriaRoute._addFileChildren(
  ControladoriaRouteChildren,
)

interface ConfiguracaoGeralRouteChildren {
  ConfiguracaoGeralCargosRoute: typeof ConfiguracaoGeralCargosRoute
  ConfiguracaoGeralIndexRoute: typeof ConfiguracaoGeralIndexRoute
  ConfiguracaoGeralPerguntasRoute: typeof ConfiguracaoGeralPerguntasRoute
  ConfiguracaoGeralPesquisadoresRoute: typeof ConfiguracaoGeralPesquisadoresRoute
}

const ConfiguracaoGeralRouteChildren: ConfiguracaoGeralRouteChildren = {
  ConfiguracaoGeralCargosRoute: ConfiguracaoGeralCargosRoute,
  ConfiguracaoGeralIndexRoute: ConfiguracaoGeralIndexRoute,
  ConfiguracaoGeralPerguntasRoute: ConfiguracaoGeralPerguntasRoute,
  ConfiguracaoGeralPesquisadoresRoute: ConfiguracaoGeralPesquisadoresRoute,
}

const ConfiguracaoGeralRouteWithChildren =
  ConfiguracaoGeralRoute._addFileChildren(ConfiguracaoGeralRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControladoriaRoute: ControladoriaRouteWithChildren,
  ConfiguracaoGeralRoute: ConfiguracaoGeralRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FinanceiroRoute: FinanceiroRouteWithChildren,
  JuridicoRoute: JuridicoRouteWithChildren,
  RevisorRoute: RevisorRouteWithChildren,
  ProjetosIdRoute: ProjetosIdRoute,
  ProjetosNovoRoute: ProjetosNovoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
