/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RevisorRouteImport } from './routes/revisor'
import { Route as JuridicoRouteImport } from './routes/juridico'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosNovoRouteImport } from './routes/projetos.novo'
import { Route as ProjetosIdRouteImport } from './routes/projetos.$id'
import { Route as RevisorProjetosIdRouteImport } from './routes/revisor.projetos.$id'
import { Route as JuridicoFinalizadosRouteImport } from './routes/juridico.finalizados'
import { Route as FinanceiroProjetosIdRouteImport } from './routes/financeiro.projetos.$id'
import { Route as JuridicoProjetosIdRouteImport } from './routes/juridico.projetos.$id'

const RevisorRoute = RevisorRouteImport.update({
  id: '/revisor',
  path: '/revisor',
  getParentRoute: () => rootRouteImport,
} as any)
const JuridicoRoute = JuridicoRouteImport.update({
  id: '/juridico',
  path: '/juridico',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosNovoRoute = ProjetosNovoRouteImport.update({
  id: '/projetos/novo',
  path: '/projetos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdRoute = ProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisorProjetosIdRoute = RevisorProjetosIdRouteImport.update({
  id: '/revisor/projetos/$id',
  path: '/revisor/projetos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JuridicoFinalizadosRoute = JuridicoFinalizadosRouteImport.update({
  id: '/juridico/finalizados',
  path: '/juridico/finalizados',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroProjetosIdRoute = FinanceiroProjetosIdRouteImport.update({
  id: '/financeiro/projetos/$id',
  path: '/financeiro/projetos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JuridicoProjetosIdRoute = JuridicoProjetosIdRouteImport.update({
  id: '/juridico/projetos/$id',
  path: '/juridico/projetos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/financeiro': typeof FinanceiroRoute
  '/juridico': typeof JuridicoRoute
  '/revisor': typeof RevisorRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/revisor/projetos/$id': typeof RevisorProjetosIdRoute
  '/juridico/finalizados': typeof JuridicoFinalizadosRoute
  '/financeiro/projetos/$id': typeof FinanceiroProjetosIdRoute
  '/juridico/projetos/$id': typeof JuridicoProjetosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/financeiro': typeof FinanceiroRoute
  '/juridico': typeof JuridicoRoute
  '/revisor': typeof RevisorRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/revisor/projetos/$id': typeof RevisorProjetosIdRoute
  '/juridico/finalizados': typeof JuridicoFinalizadosRoute
  '/financeiro/projetos/$id': typeof FinanceiroProjetosIdRoute
  '/juridico/projetos/$id': typeof JuridicoProjetosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/financeiro': typeof FinanceiroRoute
  '/juridico': typeof JuridicoRoute
  '/revisor': typeof RevisorRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/revisor/projetos/$id': typeof RevisorProjetosIdRoute
  '/juridico/finalizados': typeof JuridicoFinalizadosRoute
  '/financeiro/projetos/$id': typeof FinanceiroProjetosIdRoute
  '/juridico/projetos/$id': typeof JuridicoProjetosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/financeiro'
    | '/juridico'
    | '/revisor'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/revisor/projetos/$id'
    | '/juridico/finalizados'
    | '/financeiro/projetos/$id'
    | '/juridico/projetos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/financeiro'
    | '/juridico'
    | '/revisor'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/revisor/projetos/$id'
    | '/juridico/finalizados'
    | '/financeiro/projetos/$id'
    | '/juridico/projetos/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/financeiro'
    | '/juridico'
    | '/revisor'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/revisor/projetos/$id'
    | '/juridico/finalizados'
    | '/financeiro/projetos/$id'
    | '/juridico/projetos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FinanceiroRoute: typeof FinanceiroRoute
  JuridicoRoute: typeof JuridicoRoute
  RevisorRoute: typeof RevisorRoute
  ProjetosIdRoute: typeof ProjetosIdRoute
  ProjetosNovoRoute: typeof ProjetosNovoRoute
  RevisorProjetosIdRoute: typeof RevisorProjetosIdRoute
  JuridicoFinalizadosRoute: typeof JuridicoFinalizadosRoute
  FinanceiroProjetosIdRoute: typeof FinanceiroProjetosIdRoute
  JuridicoProjetosIdRoute: typeof JuridicoProjetosIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/revisor': {
      id: '/revisor'
      path: '/revisor'
      fullPath: '/revisor'
      preLoaderRoute: typeof RevisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juridico': {
      id: '/juridico'
      path: '/juridico'
      fullPath: '/juridico'
      preLoaderRoute: typeof JuridicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/novo': {
      id: '/projetos/novo'
      path: '/projetos/novo'
      fullPath: '/projetos/novo'
      preLoaderRoute: typeof ProjetosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$id': {
      id: '/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof ProjetosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisor/projetos/$id': {
      id: '/revisor/projetos/$id'
      path: '/revisor/projetos/$id'
      fullPath: '/revisor/projetos/$id'
      preLoaderRoute: typeof RevisorProjetosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juridico/finalizados': {
      id: '/juridico/finalizados'
      path: '/juridico/finalizados'
      fullPath: '/juridico/finalizados'
      preLoaderRoute: typeof JuridicoFinalizadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/projetos/$id': {
      id: '/financeiro/projetos/$id'
      path: '/financeiro/projetos/$id'
      fullPath: '/financeiro/projetos/$id'
      preLoaderRoute: typeof FinanceiroProjetosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juridico/projetos/$id': {
      id: '/juridico/projetos/$id'
      path: '/juridico/projetos/$id'
      fullPath: '/juridico/projetos/$id'
      preLoaderRoute: typeof JuridicoProjetosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FinanceiroRoute: FinanceiroRoute,
  JuridicoRoute: JuridicoRoute,
  RevisorRoute: RevisorRoute,
  ProjetosIdRoute: ProjetosIdRoute,
  ProjetosNovoRoute: ProjetosNovoRoute,
  RevisorProjetosIdRoute: RevisorProjetosIdRoute,
  JuridicoFinalizadosRoute: JuridicoFinalizadosRoute,
  FinanceiroProjetosIdRoute: FinanceiroProjetosIdRoute,
  JuridicoProjetosIdRoute: JuridicoProjetosIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
