/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RevisorRouteImport } from './routes/revisor'
import { Route as JuridicoRouteImport } from './routes/juridico'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RevisorIndexRouteImport } from './routes/revisor.index'
import { Route as JuridicoIndexRouteImport } from './routes/juridico.index'
import { Route as FinanceiroIndexRouteImport } from './routes/financeiro.index'
import { Route as ProjetosNovoRouteImport } from './routes/projetos.novo'
import { Route as ProjetosIdRouteImport } from './routes/projetos.$id'
import { Route as JuridicoFinalRouteImport } from './routes/juridico.final'
import { Route as JuridicoFinalIndexRouteImport } from './routes/juridico.final.index'
import { Route as RevisorProjetosIdRouteImport } from './routes/revisor.projetos.$id'
import { Route as JuridicoProjetosIdRouteImport } from './routes/juridico.projetos.$id'
import { Route as JuridicoFinalNovoRouteImport } from './routes/juridico.final.novo'
import { Route as JuridicoFinalIdRouteImport } from './routes/juridico.final.$id'
import { Route as FinanceiroProjetosIdRouteImport } from './routes/financeiro.projetos.$id'

const RevisorRoute = RevisorRouteImport.update({
  id: '/revisor',
  path: '/revisor',
  getParentRoute: () => rootRouteImport,
} as any)
const JuridicoRoute = JuridicoRouteImport.update({
  id: '/juridico',
  path: '/juridico',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisorIndexRoute = RevisorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RevisorRoute,
} as any)
const JuridicoIndexRoute = JuridicoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JuridicoRoute,
} as any)
const FinanceiroIndexRoute = FinanceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceiroRoute,
} as any)
const ProjetosNovoRoute = ProjetosNovoRouteImport.update({
  id: '/projetos/novo',
  path: '/projetos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdRoute = ProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JuridicoFinalRoute = JuridicoFinalRouteImport.update({
  id: '/final',
  path: '/final',
  getParentRoute: () => JuridicoRoute,
} as any)
const JuridicoFinalIndexRoute = JuridicoFinalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JuridicoFinalRoute,
} as any)
const RevisorProjetosIdRoute = RevisorProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => RevisorRoute,
} as any)
const JuridicoProjetosIdRoute = JuridicoProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => JuridicoRoute,
} as any)
const JuridicoFinalNovoRoute = JuridicoFinalNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => JuridicoFinalRoute,
} as any)
const JuridicoFinalIdRoute = JuridicoFinalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JuridicoFinalRoute,
} as any)
const FinanceiroProjetosIdRoute = FinanceiroProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => FinanceiroRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/juridico': typeof JuridicoRouteWithChildren
  '/revisor': typeof RevisorRouteWithChildren
  '/juridico/final': typeof JuridicoFinalRouteWithChildren
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/financeiro/': typeof FinanceiroIndexRoute
  '/juridico/': typeof JuridicoIndexRoute
  '/revisor/': typeof RevisorIndexRoute
  '/financeiro/projetos/$id': typeof FinanceiroProjetosIdRoute
  '/juridico/final/$id': typeof JuridicoFinalIdRoute
  '/juridico/final/novo': typeof JuridicoFinalNovoRoute
  '/juridico/projetos/$id': typeof JuridicoProjetosIdRoute
  '/revisor/projetos/$id': typeof RevisorProjetosIdRoute
  '/juridico/final/': typeof JuridicoFinalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/financeiro': typeof FinanceiroIndexRoute
  '/juridico': typeof JuridicoIndexRoute
  '/revisor': typeof RevisorIndexRoute
  '/financeiro/projetos/$id': typeof FinanceiroProjetosIdRoute
  '/juridico/final/$id': typeof JuridicoFinalIdRoute
  '/juridico/final/novo': typeof JuridicoFinalNovoRoute
  '/juridico/projetos/$id': typeof JuridicoProjetosIdRoute
  '/revisor/projetos/$id': typeof RevisorProjetosIdRoute
  '/juridico/final': typeof JuridicoFinalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/juridico': typeof JuridicoRouteWithChildren
  '/revisor': typeof RevisorRouteWithChildren
  '/juridico/final': typeof JuridicoFinalRouteWithChildren
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/financeiro/': typeof FinanceiroIndexRoute
  '/juridico/': typeof JuridicoIndexRoute
  '/revisor/': typeof RevisorIndexRoute
  '/financeiro/projetos/$id': typeof FinanceiroProjetosIdRoute
  '/juridico/final/$id': typeof JuridicoFinalIdRoute
  '/juridico/final/novo': typeof JuridicoFinalNovoRoute
  '/juridico/projetos/$id': typeof JuridicoProjetosIdRoute
  '/revisor/projetos/$id': typeof RevisorProjetosIdRoute
  '/juridico/final/': typeof JuridicoFinalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/financeiro'
    | '/juridico'
    | '/revisor'
    | '/juridico/final'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/financeiro/'
    | '/juridico/'
    | '/revisor/'
    | '/financeiro/projetos/$id'
    | '/juridico/final/$id'
    | '/juridico/final/novo'
    | '/juridico/projetos/$id'
    | '/revisor/projetos/$id'
    | '/juridico/final/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/financeiro'
    | '/juridico'
    | '/revisor'
    | '/financeiro/projetos/$id'
    | '/juridico/final/$id'
    | '/juridico/final/novo'
    | '/juridico/projetos/$id'
    | '/revisor/projetos/$id'
    | '/juridico/final'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/financeiro'
    | '/juridico'
    | '/revisor'
    | '/juridico/final'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/financeiro/'
    | '/juridico/'
    | '/revisor/'
    | '/financeiro/projetos/$id'
    | '/juridico/final/$id'
    | '/juridico/final/novo'
    | '/juridico/projetos/$id'
    | '/revisor/projetos/$id'
    | '/juridico/final/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FinanceiroRoute: typeof FinanceiroRouteWithChildren
  JuridicoRoute: typeof JuridicoRouteWithChildren
  RevisorRoute: typeof RevisorRouteWithChildren
  ProjetosIdRoute: typeof ProjetosIdRoute
  ProjetosNovoRoute: typeof ProjetosNovoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/revisor': {
      id: '/revisor'
      path: '/revisor'
      fullPath: '/revisor'
      preLoaderRoute: typeof RevisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juridico': {
      id: '/juridico'
      path: '/juridico'
      fullPath: '/juridico'
      preLoaderRoute: typeof JuridicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisor/': {
      id: '/revisor/'
      path: '/'
      fullPath: '/revisor/'
      preLoaderRoute: typeof RevisorIndexRouteImport
      parentRoute: typeof RevisorRoute
    }
    '/juridico/': {
      id: '/juridico/'
      path: '/'
      fullPath: '/juridico/'
      preLoaderRoute: typeof JuridicoIndexRouteImport
      parentRoute: typeof JuridicoRoute
    }
    '/financeiro/': {
      id: '/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof FinanceiroIndexRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/projetos/novo': {
      id: '/projetos/novo'
      path: '/projetos/novo'
      fullPath: '/projetos/novo'
      preLoaderRoute: typeof ProjetosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$id': {
      id: '/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof ProjetosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juridico/final': {
      id: '/juridico/final'
      path: '/final'
      fullPath: '/juridico/final'
      preLoaderRoute: typeof JuridicoFinalRouteImport
      parentRoute: typeof JuridicoRoute
    }
    '/juridico/final/': {
      id: '/juridico/final/'
      path: '/'
      fullPath: '/juridico/final/'
      preLoaderRoute: typeof JuridicoFinalIndexRouteImport
      parentRoute: typeof JuridicoFinalRoute
    }
    '/revisor/projetos/$id': {
      id: '/revisor/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/revisor/projetos/$id'
      preLoaderRoute: typeof RevisorProjetosIdRouteImport
      parentRoute: typeof RevisorRoute
    }
    '/juridico/projetos/$id': {
      id: '/juridico/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/juridico/projetos/$id'
      preLoaderRoute: typeof JuridicoProjetosIdRouteImport
      parentRoute: typeof JuridicoRoute
    }
    '/juridico/final/novo': {
      id: '/juridico/final/novo'
      path: '/novo'
      fullPath: '/juridico/final/novo'
      preLoaderRoute: typeof JuridicoFinalNovoRouteImport
      parentRoute: typeof JuridicoFinalRoute
    }
    '/juridico/final/$id': {
      id: '/juridico/final/$id'
      path: '/$id'
      fullPath: '/juridico/final/$id'
      preLoaderRoute: typeof JuridicoFinalIdRouteImport
      parentRoute: typeof JuridicoFinalRoute
    }
    '/financeiro/projetos/$id': {
      id: '/financeiro/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/financeiro/projetos/$id'
      preLoaderRoute: typeof FinanceiroProjetosIdRouteImport
      parentRoute: typeof FinanceiroRoute
    }
  }
}

interface FinanceiroRouteChildren {
  FinanceiroIndexRoute: typeof FinanceiroIndexRoute
  FinanceiroProjetosIdRoute: typeof FinanceiroProjetosIdRoute
}

const FinanceiroRouteChildren: FinanceiroRouteChildren = {
  FinanceiroIndexRoute: FinanceiroIndexRoute,
  FinanceiroProjetosIdRoute: FinanceiroProjetosIdRoute,
}

const FinanceiroRouteWithChildren = FinanceiroRoute._addFileChildren(
  FinanceiroRouteChildren,
)

interface JuridicoFinalRouteChildren {
  JuridicoFinalIdRoute: typeof JuridicoFinalIdRoute
  JuridicoFinalNovoRoute: typeof JuridicoFinalNovoRoute
  JuridicoFinalIndexRoute: typeof JuridicoFinalIndexRoute
}

const JuridicoFinalRouteChildren: JuridicoFinalRouteChildren = {
  JuridicoFinalIdRoute: JuridicoFinalIdRoute,
  JuridicoFinalNovoRoute: JuridicoFinalNovoRoute,
  JuridicoFinalIndexRoute: JuridicoFinalIndexRoute,
}

const JuridicoFinalRouteWithChildren = JuridicoFinalRoute._addFileChildren(
  JuridicoFinalRouteChildren,
)

interface JuridicoRouteChildren {
  JuridicoFinalRoute: typeof JuridicoFinalRouteWithChildren
  JuridicoIndexRoute: typeof JuridicoIndexRoute
  JuridicoProjetosIdRoute: typeof JuridicoProjetosIdRoute
}

const JuridicoRouteChildren: JuridicoRouteChildren = {
  JuridicoFinalRoute: JuridicoFinalRouteWithChildren,
  JuridicoIndexRoute: JuridicoIndexRoute,
  JuridicoProjetosIdRoute: JuridicoProjetosIdRoute,
}

const JuridicoRouteWithChildren = JuridicoRoute._addFileChildren(
  JuridicoRouteChildren,
)

interface RevisorRouteChildren {
  RevisorIndexRoute: typeof RevisorIndexRoute
  RevisorProjetosIdRoute: typeof RevisorProjetosIdRoute
}

const RevisorRouteChildren: RevisorRouteChildren = {
  RevisorIndexRoute: RevisorIndexRoute,
  RevisorProjetosIdRoute: RevisorProjetosIdRoute,
}

const RevisorRouteWithChildren =
  RevisorRoute._addFileChildren(RevisorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FinanceiroRoute: FinanceiroRouteWithChildren,
  JuridicoRoute: JuridicoRouteWithChildren,
  RevisorRoute: RevisorRouteWithChildren,
  ProjetosIdRoute: ProjetosIdRoute,
  ProjetosNovoRoute: ProjetosNovoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
